# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        script:
          - node -v
  branches:
    master:
     - step:
        name: add dependencies
        caches:
         - node
        script:
          - yarn install
     - step:
        name: build optimized package
        script:
         - yarn run build:prod
     - step:
        name: deploy to production
        deployment: Production
        script:
         - pipe: atlassian/firebase-deploy:0.3.3
           variables:
             FIREBASE_TOKEN: $FIREBASE_TOKEN
             PROJECT_ID: 'prod'
             # MESSAGE: '<string>' # Optional.
             # EXTRA_ARGS: '<string>' # Optional.
             DEBUG: 'true' # Optional.
         - echo 'deployment to production complete'
    develop:
     - step:
        name: deploy to dev
        deployment: Development
        caches:
          - node
        script:
         - yarn install
         - yarn run build:dev
         - pipe: atlassian/firebase-deploy:0.3.3
           variables:
             FIREBASE_TOKEN: $FIREBASE_TOKEN
             PROJECT_ID: 'dev'
             # MESSAGE: '<string>' # Optional.
             # EXTRA_ARGS: '<string>' # Optional.
             DEBUG: 'true' # Optional.
         - echo 'deployment to dev complete'
    staging:
     - step:
        name: deploy to staging
        deployment: Staging
        caches:
          - node
        script:
         - yarn install
         - yarn run build:staging
         - pipe: atlassian/firebase-deploy:0.3.3
           variables:
             FIREBASE_TOKEN: $FIREBASE_TOKEN
             PROJECT_ID: 'staging'
             # MESSAGE: '<string>' # Optional.
             # EXTRA_ARGS: '<string>' # Optional.
             DEBUG: 'true' # Optional.
         - echo 'deployment to staging complete'